### ISSUE TITLE
期望增加对配置文件的说明文档

### ISSUE THREAD

**Issue by systemctl529** [samwafgo/SamWaf#168]
### 产品版本

1.3.10

### 版本类型

- [x] 社区版

### ⭐️ 需求描述

期望增加一些conf配置文件的说明文档，例如日志级别的定义，外置数据库的格式等。
感谢您的项目。

**Comment by samwafgo** [comment]
conf 本地配置如下：

```yml
custom_server_name:  //默认读取的是本地服务器名称
export_download: false   //是否运行前端下载数据库db文件
local_port: 26666 // 本地管理端口
notice:
    isenable: false  //是否激活通知
soft_id: SamWafCom   //默认标识
user_code:    //本地UUID


```
