### ISSUE TITLE
文档缺少后端域名说明

### ISSUE THREAD

**Issue by redjumper** [samwafgo/SamWaf#233]
添加保护网站时，后端域名的作用是什么，文档中没有写明。
另外当关闭传递后端域名时，感觉后端域名没必要填写

**Comment by samwafgo** [comment]
后端域名默认是会同步成和主域名一样的配置，但是如果 前置和后置的站点不一样的话这个就有作用了，参考：https://github.com/samwafgo/SamWaf/issues/78

**Comment by samwafgo** [comment]
文档也更新了：https://doc.samwaf.com/guide/Host.html

**Comment by redjumper** [comment]
看了https://github.com/samwafgo/SamWaf/issues/78，后端域名并不是必须
比如下面场景
1、waf和web服务器在一个局域网中，web服务器上不配置域名，域名统一在waf处配置，只需要指定后端ip和端口，不需要后端域名。
2、waf和某个web服务都是容器方式部署，只要俩容器在一个桥接网络中，web服务并不需要对外暴露端口。这个时候也不存在后端域名
这里我给出截图和配置。minio容器并没有暴露9000端口。
另外我发现健康检查默认会使用后端域名+后端端口的方式，这种场景下，健康检查会异常

![Image](https://github.com/user-attachments/assets/c8a0dfe3-045e-4059-bfc7-26b9ad73ea46)
```
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - ${MINIO_PORT}:9001
    environment:
      - MINIO_ROOT_USER=xxx
      - MINIO_ROOT_PASSWORD=xxxxxx
      - MINIO_DOMAIN=${DOMAIN}
      - MINIO_API_CORS_ALLOW_ORIGIN=https://xxx
    networks:
      - samwaf_waf
    command: server /data --console-address ":9001"
    volumes:
      - /volume1/docker/minio/data:/data
networks:
  samwaf_waf:
    external: true
```
