### ISSUE TITLE
[Bug] docker部署samwaf时，用户访问无法记录真实IP

### ISSUE THREAD

**Issue by ShiDai567** [samwafgo/SamWaf#327]
### 产品版本

v1.3.13

### 版本类型

- [x] 社区版

### 环境信息

![Image](https://github.com/user-attachments/assets/bf8f163f-81ee-438b-a885-f1d427572973)

![Image](https://github.com/user-attachments/assets/a458830b-350e-469a-9376-daccd476b47b)

docker配置文件如下
```yml
networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "nginx_net"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
services:
  samwaf:
    image: samwaf/samwaf
    container_name: samwaf
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 8082:80 # Public HTTP Port
      - 8445:443 # Public HTTPS Port
      - 84:26666  # Admin Web Port
    volumes:
      - ${CONFIG_DIR}/samwaf/conf:/app/conf
      - ${CONFIG_DIR}/samwaf/data:/app/data
      - ${CONFIG_DIR}/samwaf/logs:/app/logs
      - ${CONFIG_DIR}/samwaf/ssl:/app/ssl
    networks:
      net:
        ipv4_address: 172.18.0.6
```

### 🐛 缺陷描述

我建了一个博客，在另一个机器上，这台机器建了您的项目反代博客，用8445/SSL访问
点开图2的详询后请求头没有X-Forwarded-For标签，以至于无法正确显示IP地址

### 期望结果

正确显示IP来源
