### ISSUE TITLE
[Feature] 增加数据库日志打印调试开关

### ISSUE THREAD

**Issue by samwafgo** [samwafgo/SamWaf#361]
### 产品版本

最新版本

### 版本类型

- [ ] 社区版

### ⭐️ 需求描述

增加数据库日志打印调试开关

### 补充信息

conf/config.yml

```
zlog:
    db_debug_enable: false
    debug_enable: false
    outputformat: console


```
db_debug_enable 数据库日志打印开关 默认false关闭，true开启；
